openshift_prometheus_image_prefix: "isolated1.56af.internal:5000/openshift3/"
openshift_prometheus_image_version: v3.9
openshift_prometheus_alertmanager_image_prefix: "isolated1.56af.internal:5000/openshift3/"
openshift_prometheus_alertmanager_image_version: v3.9
openshift_prometheus_alertbuffer_image_prefix: "isolated1.56af.internal:5000/openshift3/"
openshift_prometheus_alertbuffer_image_version: v3.9
openshift_prometheus_oauth_proxy_image_prefix: "isolated1.56af.internal:5000/openshift3/"
openshift_prometheus_oauth_proxy_image_version: v3.9

openshift_hosted_prometheus_deploy: true
openshift_prometheus_node_selector: 
  env: "infra"
openshift_prometheus_namespace: openshift-metrics

openshift_prometheus_storage_kind: nfs
openshift_prometheus_storage_access_modes:
  - 'ReadWriteOnce'
openshift_prometheus_storage_nfs_directory: "/srv/nfs"
openshift_prometheus_storage_nfs_options: '*(rw,root_squash)'
openshift_prometheus_storage_volume_name: prometheus
openshift_prometheus_storage_volume_size: 10Gi
openshift_prometheus_storage_labels: 
  storage: 'prometheus'
openshift_prometheus_storage_type: 'pvc'

openshift_prometheus_alertmanager_storage_kind: nfs
openshift_prometheus_alertmanager_storage_access_modes: 
  - 'ReadWriteOnce'
openshift_prometheus_alertmanager_storage_nfs_directory: "/srv/nfs"
openshift_prometheus_alertmanager_storage_nfs_options: '*(rw,root_squash)'
openshift_prometheus_alertmanager_storage_volume_name: prometheus-alertmanager
openshift_prometheus_alertmanager_storage_volume_size: 10Gi
openshift_prometheus_alertmanager_storage_labels:
  storage: 'prometheus-alertmanager'
openshift_prometheus_alertmanager_storage_type: 'pvc'

openshift_prometheus_alertbuffer_storage_kind: nfs
openshift_prometheus_alertbuffer_storage_access_modes: 
  - 'ReadWriteOnce'
openshift_prometheus_alertbuffer_storage_nfs_directory: "/srv/nfs"
openshift_prometheus_alertbuffer_storage_nfs_options: '*(rw,root_squash)'
openshift_prometheus_alertbuffer_storage_volume_name: prometheus-alertbuffer
openshift_prometheus_alertbuffer_storage_volume_size: 10Gi
openshift_prometheus_alertbuffer_storage_labels:
  storage: 'prometheus-alertbuffer'
openshift_prometheus_alertbuffer_storage_type: 'pvc'
